[package]
name = "mdev"
version = "0.1.0"
edition = "2018"
description = "mini-udev workalike"

[dependencies]
mdev-parser = "0.1"
kobject-uevent = "0.1"
anyhow = "1.0"
structopt = "0.3"
tracing = "0.1"
tracing-subscriber = "0.2"
netlink-sys = { version = "0.7", features = ["tokio_socket"] }
futures-util = "0.3"
tokio = { version = "1.12", features = ["macros", "rt-multi-thread"] }
fork = "0.1"
walkdir = "2"

[patch.crates-io]
mdev-parser = { git = "https://github.com/rust-italia/mdev-parser" }
kobject-uevent = { git = "https://github.com/rust-italia/kobject-uevent" }
